monolog:
    channels: ["video_stream_v1", "http_server_v1","hosts"]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
        video_stream_v1:
            channels: [ "video_stream_v1" ]
            path: "%kernel.logs_dir%/video_stream_v1.log"
            level: info
            type: rotating_file
            max_files: 5
            filename_format: "{filename}_{date}"
            date_format: "Y"
        http_server_v1:
            channels: [ "http_server_v1" ]
            path: "%kernel.logs_dir%/http/http_server_v1.log"
            level: info
            type: rotating_file
            max_files: 5
            filename_format: "{filename}_{date}"
            date_format: "Y-m"
        hosts:
            channels: [ "hosts" ]
            path: "%kernel.logs_dir%/hosts.log"
            level: info
            type: rotating_file
            max_files: 5
            filename_format: "{filename}_{date}"
            date_format: "Y-m"
